-- USUARIOS + ROL + EVENTOS + EMPRESA
SELECT 
    u.NOM_USUARIO,
    u.CORREO_USUARIO,
    r.NOM_ROL,
    ev.TITULO,
    ev.FECHA_EVENTO,
    e.NOMBRE_EMPRESA
FROM USUARIO u
JOIN USUARIO_ROL ur ON u.idUSUARIO = ur.idUSUARIO
JOIN ROL r ON ur.idROL = r.idROL
LEFT JOIN EVENTOS ev ON u.idUSUARIO = ev.idUSUARIO
LEFT JOIN EMPRESA e ON ev.idEMPRESA = e.idEMPRESA;

-- EMPRESA + PRODUCTOS + CATEGORIA
SELECT 
    e.NOMBRE_EMPRESA,
    p.NOM_PRODUCTO,
    c.NOM_CATEGORIA,
    p.PRECIO,
    p.STOCK
FROM EMPRESA e
JOIN EMPRESA_PRODUCTOS ep ON e.idEMPRESA = ep.idEMPRESA
JOIN PRODUCTO p ON ep.idPRODUCTO = p.idPRODUCTO
JOIN CATEGORIA c ON p.idCATEGORIA = c.idCATEGORIA;

-- PRODUCTO + RESEÑAS + USUARIO
SELECT 
    p.NOM_PRODUCTO,
    u.NOM_USUARIO,
    r.COMENTARIO,
    r.CALIFICACION,
    r.FECHA_PUBLICACION
FROM PRODUCTO p
JOIN RESENA r ON p.idPRODUCTO = r.idPRODUCTO
JOIN RESENA_USUARIO ru ON r.idRESENA = ru.idRESENA
JOIN USUARIO u ON ru.idUSUARIO = u.idUSUARIO;

-- PRODUCTOS + PROMEDIO DE CALIFICACIÓN
SELECT 
    p.NOM_PRODUCTO,
    c.NOM_CATEGORIA,
    AVG(r.CALIFICACION) AS promedio_calificacion,
    COUNT(r.idRESENA) AS total_resenas
FROM PRODUCTO p
JOIN CATEGORIA c ON p.idCATEGORIA = c.idCATEGORIA
LEFT JOIN RESENA r ON p.idPRODUCTO = r.idPRODUCTO
GROUP BY p.idPRODUCTO;

-- REPORTES + PRODUCTO + USUARIO + TIPO
SELECT 
    tr.NOM_REPORTE,
    p.NOM_PRODUCTO,
    u.NOM_USUARIO,
    rep.RAZON_REPORTE,
    rep.REGISTRO_REPORTE
FROM REPORTES rep
JOIN TIP_REPORTE tr ON rep.idTIP_REPORTE = tr.idTIP_REPORTE
JOIN PRODUCTO p ON rep.idPRODUCTO = p.idPRODUCTO
JOIN USUARIO u ON rep.idUSUARIO = u.idUSUARIO;
se
-- CONSULTA COMPLETA (TIPO DASHBOARD)
SELECT 
    u.NOM_USUARIO,
    r2.NOM_ROL,
    e.NOMBRE_EMPRESA,
    p.NOM_PRODUCTO,
    c.NOM_CATEGORIA,
    p.PRECIO,
    re.COMENTARIO,
    re.CALIFICACION
FROM USUARIO u
JOIN USUARIO_ROL ur ON u.idUSUARIO = ur.idUSUARIO
JOIN ROL r2 ON ur.idROL = r2.idROL
LEFT JOIN EMPRESA e ON u.idUSUARIO = e.idUSUARIO
LEFT JOIN EMPRESA_PRODUCTOS ep ON e.idEMPRESA = ep.idEMPRESA
LEFT JOIN PRODUCTO p ON ep.idPRODUCTO = p.idPRODUCTO
LEFT JOIN CATEGORIA c ON p.idCATEGORIA = c.idCATEGORIA
LEFT JOIN RESENA re ON p.idPRODUCTO = re.idPRODUCTO;