DROP DATABASE IF EXISTS Nexus;
CREATE DATABASE Nexus DEFAULT CHARACTER SET utf8;
USE Nexus;

-- 1. Tabla USUARIO
CREATE TABLE IF NOT EXISTS USUARIO (
  idUSUARIO INT NOT NULL AUTO_INCREMENT,
  NOM_USUARIO VARCHAR(30) NOT NULL,
  CORREO_USUARIO VARCHAR(70) NOT NULL,
  CONTRASENA VARCHAR(50) NOT NULL,
  APELLIDO VARCHAR(30) NOT NULL,
  FECHA_REGISTRO DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (idUSUARIO)
) ENGINE = InnoDB;

-- 2. Tabla ROL
CREATE TABLE IF NOT EXISTS ROL (
  idROL INT NOT NULL,
  NOM_ROL VARCHAR(50) NOT NULL,
  PRIMARY KEY (idROL)
) ENGINE = InnoDB;

-- 3. Tabla CATEGORIA
CREATE TABLE IF NOT EXISTS CATEGORIA (
  idCATEGORIA INT NOT NULL AUTO_INCREMENT,
  NOM_CATEGORIA VARCHAR(45) NOT NULL,
  DESC_CATEGORIA TEXT NOT NULL,
  PRIMARY KEY (idCATEGORIA)
) ENGINE = InnoDB;

-- 4. Tabla EMPRESA
CREATE TABLE IF NOT EXISTS EMPRESA (
  idUSUARIO INT NOT NULL,
  idEMPRESA INT NOT NULL AUTO_INCREMENT,
  CORREO_EMPRESA VARCHAR(100) NOT NULL,
  LOGO VARCHAR(360) NOT NULL,
  NOMBRE_EMPRESA VARCHAR(60) NOT NULL,
  DESCRIPCION TEXT NOT NULL,
  DIRECCION VARCHAR(150) NOT NULL,
  FECHA_REGISTRO DATETIME(6) NOT NULL,
  PRIMARY KEY (idEMPRESA),
  CONSTRAINT fr_empresa_usuario FOREIGN KEY (idUSUARIO)
    REFERENCES USUARIO (idUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 5. Tabla PRODUCTO (Sin la columna idRESEÑA para evitar error circular)
CREATE TABLE IF NOT EXISTS PRODUCTO (
  idPRODUCTO INT NOT NULL AUTO_INCREMENT,
  idCATEGORIA INT NOT NULL,
  NOM_PRODUCTO VARCHAR(45) NOT NULL,
  PRECIO INT NOT NULL,
  DIA_PUBLICACION DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  STOCK INT NOT NULL,
  ESTADO_ITEM ENUM('DISPONIBLE', 'AGOTADO', 'INACTIVO') NOT NULL DEFAULT 'DISPONIBLE',
  IMAGEN_PRODUCTO VARCHAR(450) NOT NULL,
  TIPO_ITEM ENUM('Producto', 'Servicio') NULL,
  PRIMARY KEY (idPRODUCTO),
  INDEX FR_producto_categoria_idx (idCATEGORIA ASC),
  CONSTRAINT fr_producto_categoria FOREIGN KEY (idCATEGORIA)
    REFERENCES CATEGORIA (idCATEGORIA) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 6. Tabla RESENA (Esta ya referencia a PRODUCTO)
CREATE TABLE IF NOT EXISTS RESENA (
  idRESENA INT NOT NULL AUTO_INCREMENT,
  idPRODUCTO INT NOT NULL,
  COMENTARIO TEXT NOT NULL,
  CALIFICACION INT NOT NULL,
  FECHA_PUBLICACION DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (idRESENA),
  CONSTRAINT fr_resena_producto FOREIGN KEY (idPRODUCTO)
    REFERENCES PRODUCTO (idPRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 7. Tabla EMPRESA_PRODUCTOS
CREATE TABLE IF NOT EXISTS EMPRESA_PRODUCTOS (
  idEMPRESA_PRODUCTOS INT NOT NULL AUTO_INCREMENT,
  idPRODUCTO INT NOT NULL,
  idEMPRESA INT NOT NULL,
  PRIMARY KEY (idEMPRESA_PRODUCTOS),
  CONSTRAINT fr_empro_empresa FOREIGN KEY (idEMPRESA)
    REFERENCES EMPRESA (idEMPRESA) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fr_empro_producto FOREIGN KEY (idPRODUCTO)
    REFERENCES PRODUCTO (idPRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 8. Tabla USUARIO_ROL
CREATE TABLE IF NOT EXISTS USUARIO_ROL (
  idUSUARIO_ROL INT NOT NULL,
  idUSUARIO INT NOT NULL,
  idROL INT NOT NULL,
  PRIMARY KEY (idUSUARIO_ROL),
  CONSTRAINT fr_usrol_usuario FOREIGN KEY (idUSUARIO)
    REFERENCES USUARIO (idUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fr_usrol_rol FOREIGN KEY (idROL)
    REFERENCES ROL (idROL) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 9. Tabla EVENTOS
CREATE TABLE IF NOT EXISTS EVENTOS (
  idEVENTOS INT NOT NULL AUTO_INCREMENT,
  TITULO VARCHAR(60) NOT NULL,
  DESCRIPCION TEXT NOT NULL,
  FECHA_EVENTO DATE NOT NULL,
  FECHA_HORA TIME NULL,
  LUGAR VARCHAR(90) NULL,
  ESTADO ENUM('ACTIVO', 'CANCELADO', 'FINALIZADO') NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  idUSUARIO INT NOT NULL,
  idEMPRESA INT NOT NULL,
  PRIMARY KEY (idEVENTOS),
  CONSTRAINT fr_eventos_usuario FOREIGN KEY (idUSUARIO)
    REFERENCES USUARIO (idUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fr_eventos_empresa FOREIGN KEY (idEMPRESA)
    REFERENCES EMPRESA (idEMPRESA) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 10. Tabla RESENA_USUARIO
CREATE TABLE IF NOT EXISTS RESENA_USUARIO (
  idRESENA_USUARIO INT NOT NULL AUTO_INCREMENT,
  idRESENA INT NOT NULL,
  idUSUARIO INT NOT NULL,
  PRIMARY KEY (idRESENA_USUARIO),
  CONSTRAINT fr_reseusu_resena FOREIGN KEY (idRESENA)
    REFERENCES RESENA (idRESENA) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fr_reseusu_usuario FOREIGN KEY (idUSUARIO)
    REFERENCES USUARIO (idUSUARIO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- 11. Tabla TIP_REPORTE
CREATE TABLE IF NOT EXISTS TIP_REPORTE (
  idTIP_REPORTE INT NOT NULL,
  NOM_REPORTE VARCHAR(45) NOT NULL,
  DESCRICION TEXT NOT NULL,
  PRIMARY KEY (idTIP_REPORTE)
) ENGINE = InnoDB;

-- 12. Tabla REPORTES
CREATE TABLE IF NOT EXISTS REPORTES (
  idREPORTES INT NOT NULL,
  idTIP_REPORTE INT NOT NULL,
  idPRODUCTO INT NOT NULL,
  RAZON_REPORTE TEXT NOT NULL,
  REGISTRO_REPORTE DATETIME(6) NOT NULL,
  idUSUARIO INT NOT NULL,
  PRIMARY KEY (idREPORTES),
  CONSTRAINT fk_reporte_tip_reporte FOREIGN KEY (idTIP_REPORTE)
    REFERENCES TIP_REPORTE (idTIP_REPORTE),
  CONSTRAINT fk_reporte_producto FOREIGN KEY (idPRODUCTO)
    REFERENCES PRODUCTO (idPRODUCTO),
  CONSTRAINT fk_Reporte_Usuario FOREIGN KEY (idUSUARIO)
    REFERENCES USUARIO (idUSUARIO)
) ENGINE = InnoDB;