use Nexus;
-- Productos con precio mayor al promedio
SELECT NOM_PRODUCTO, PRECIO
FROM PRODUCTO
WHERE PRECIO > (SELECT AVG(PRECIO) FROM PRODUCTO);

-- Usuarios que han comprado productos
SELECT NOM_USUARIO, CORREO_USUARIO
FROM USUARIO
WHERE idUSUARIO IN (
    SELECT DISTINCT idUSUARIO 
    FROM EVENTOS 
    WHERE TITULO LIKE 'Compra%'
);

-- Empresas que tienen productos con reseñas
SELECT NOMBRE_EMPRESA
FROM EMPRESA E
WHERE EXISTS (
    SELECT 1 
    FROM EMPRESA_PRODUCTOS EP
    JOIN PRODUCTO P ON EP.idPRODUCTO = P.idPRODUCTO
    JOIN RESENA R ON P.idPRODUCTO = R.idPRODUCTO
    WHERE EP.idEMPRESA = E.idEMPRESA
);

-- Productos más caros que TODOS los de categoría 'Moda'
SELECT NOM_PRODUCTO, PRECIO
FROM PRODUCTO
WHERE PRECIO > ALL (
    SELECT PRECIO 
    FROM PRODUCTO P
    JOIN CATEGORIA C ON P.idCATEGORIA = C.idCATEGORIA
    WHERE C.NOM_CATEGORIA = 'Moda'
);

-- Productos con mismo precio y stock que algún producto con stock > 100
SELECT NOM_PRODUCTO, PRECIO, STOCK
FROM PRODUCTO
WHERE (PRECIO, STOCK) = ANY (
    SELECT PRECIO, STOCK
    FROM PRODUCTO
    WHERE STOCK > 100
);
